[project]
name = "youtube-vid-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=5.5",
    "pipenv>=2025.0.2",
    "pytubefix>=8.13.1",
    "schedule>=1.2.2",
    "tqdm>=4.67.1",
]
